[package]
name = "sal_app"
version = "0.1.0"
authors = ["Michael Mullin <mimullin@blackberry.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19"
rocket = "0.4.6"
