[package]
name = "sal_app"
version = "0.1.0"
authors = ["Michael Mullin <mimullin@blackberry.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
rocket = "0.5.0-rc.2"
